Initial Commit
wavefrontHQ/wavefront-sdk-cpp pull request #1
Opened 2018-09-25 22:03 UTC by mengranwo

Add Tier 1 C++ SDK to send metrics/histograms/opentracing-spans/events to Wavefront via proxy/direct-ingestion.  
Please read **README** for more detailed usage scenario 

TODO : 
* add test cases

2018-09-27 05:47 UTC, sushantdewan123 requested changes

2018-09-27 05:47 UTC, sushantdewan123 commented on README.md
> +  // 2) Send Direct Distribution (Histogram) to Wavefront
You should also have sample code for 
// 2) Send Delta Counter to Wavefront     

see the README for https://github.com/wavefrontHQ/wavefront-java-sdk

2018-09-27 05:47 UTC, sushantdewan123 commented on src/include/common/WavefrontSender.h
> +        sendMetric(const std::string &name, double value, long timestamp = -1, const std::string &source = "",
you should also support sendDelta method
see https://github.com/wavefrontHQ/wavefront-java-sdk/blob/master/src/main/java/com/wavefront/sdk/entities/metrics/WavefrontMetricSender.java#L51

2018-09-27 05:47 UTC, sushantdewan123 commented on src/proxy/ProxyConnectionHandler.cpp
> +    ProxyConnectionHandler::ProxyConnectionHandler(std::string &hostName, unsigned short port) : hostName(hostName),
might want to stick to 100 char limit else i have to scroll on github to read your code.

2018-10-05 22:25 UTC, jbau requested changes

2018-10-05 22:25 UTC, jbau commented on src/direct_ingestion/WavefrontDirectIngestionClient.cpp
> +                std::cerr << "Buffer full, dropping metrics: " << lineData << std::endl;
can we force a push here rather than drop the points?

2018-10-05 22:25 UTC, jbau commented on src/common/Socket.cpp
> +    }
should it try a couple of times to reconnect before giving up?

2018-10-05 22:25 UTC, jbau commented on src/common/Socket.cpp
> +    }
seems like that's the java behavior also

2018-10-05 22:25 UTC, jbau commented on src/direct_ingestion/WavefrontDirectIngestionClient.cpp
> +                std::cerr << "Buffer full, dropping metrics: " << lineData << std::endl;
i see that the java sdk also drops when the buffer is full @vikramraman 

did we consider having that force a push instead?

2018-10-05 22:25 UTC, jbau commented on src/include/direct_ingestion/WavefrontDirectIngestionClient.h
> +            int batchSize = 10000;
please adjust these defaults to match the java.  i think it's 5000 / 1000

2018-10-05 22:28 UTC, mengranwo commented on src/include/direct_ingestion/WavefrontDirectIngestionClient.h
> +            int batchSize = 10000;
done!

2018-10-09 16:20 UTC, mengranwo commented on src/common/Socket.cpp
> +    }
done!

2018-10-17 19:52 UTC, vikramraman approved these changes

2018-10-17 19:52 UTC, vikramraman commented
Merging as the review comments have been addressed.

2018-10-17 19:53 UTC, merged